config/routes.rb
SquashSimulator::Application.routes.draw do
  root :to => 'home#index'

  resources :users

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/simulation' => 'pages#simulation'
  get '/datatable' => 'pages#datatable'
  get '/team_lookup' => 'pages#scrape'
  get '/rankings' => 'pages#rankings'
  get '/ladder' => 'pages#ladder'
  get '/update' => 'pages#get_most_recent_ladder'
end

app/models/ladder.rb
class Ladder < ActiveRecord::Base
  attr_accessible :ordered_list
  serialize :ordered_list, Array
end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :name, :rating, :team
end

app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  team_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Team < ActiveRecord::Base
  attr_accessible :name, :team_id, :ranking
  scope :sorted, order("name asc")
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)
#  password_digest :string(255)
#  team            :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :password, :password_confirmation, :team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate
  private
  def authenticate
    @auth = User.find(session[:user_id]) if session[:user_id].present?
  end
  def ensure_logged_in
    redirect_to(root_path) if @auth.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  require 'open-uri'

  def simulation
    @top_80 = Team.all
    @top_20 = Team.where("ranking > 0 AND ranking < 21")
  end

  def ladder
    #if Ladder.exists? && Ladder.all.first.ordered_list.length != 0
    #  most_recent = Ladder.all.order('created_at').last
    #  @ladder = most_recent
    #else
    get_most_recent_ladder
    #end
  end

  def get_most_recent_ladder
    @top_80 = Team.all
    # loop through all teams, add each player and their rating to the hash, sort by rating, limit to 200
    all_players = []

    @top_80.each do |team|
      url = "http://modules.ussquash.com/ssm/pages/leagues/Team_Information.asp?id=#{team.team_id}"
      doc = Nokogiri::HTML(open(url))
      player_names = doc.css('.table.table-bordered.table-striped.table-condensed')[1].css('tr td a').map(&:content)
      for i in (0..player_names.length-1)
        comma_index = player_names[i] =~ /,/
        first_name = []
        last_name = []
        (0..comma_index-1).each do |index|
          last_name << player_names[i][index]
        end
        last_name = last_name.join()
        (comma_index+1..player_names[i].length-1).each do |index|
          first_name << player_names[i][index]
        end
        first_name = first_name.join()
        full_name = first_name + ' ' + last_name
        player_names[i] = full_name
      end
      player_ratings = doc.css('.table.table-bordered.table-striped.table-condensed')[1].css('tr td:nth-child(4)').map(&:content)
      for i in (0..player_names.length-1)
        player = Player.create(:name => player_names[i], :rating => player_ratings[i].to_f, :team => team.name)
        all_players << player
      end
    end

    all_players = all_players.sort{|player1, player2| player1.rating <=> player2.rating}.reverse.first(100)
    #insert creation of ladder object with order
    @ladder = all_players
    render 'ladder'
  end

  def scrape
    team1 = params[:first_team]
    team2 = params[:second_team]
    two_teams = []
    collection = [team1, team2].each do |team|
      url = "http://modules.ussquash.com/ssm/pages/leagues/Team_Information.asp?id=#{team}"

      doc = Nokogiri::HTML(open(url))
      player_names = doc.css('.table.table-bordered.table-striped.table-condensed')[1].css('tr td a').map(&:content)
      player_ratings = doc.css('.table.table-bordered.table-striped.table-condensed')[1].css('tr td:nth-child(4)').map(&:content)

      player_hash = {}
      for i in (0..player_names.length-1)
        player_hash[player_names[i]] = player_ratings[i]
      end
      player_hash = player_hash.sort_by{|key, value| value}.reverse.first(9)
      two_teams << player_hash
    end
    render :json => {teams: two_teams}
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
  def create
    user = User.where(:email => params[:email]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to(root_path)
    else
      redirect_to(login_path)
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to(root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(:email)
  end
  def new
    @user = User.new
  end
  def create
    User.create(params[:user])
    @users = User.order(:email)
    respond_to do |format|
      format.html { redirect_to(users_path) }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def intellinav
    if @auth.present?
      link_to(@auth.email, login_path, :method => :delete, :class => 'button')
    else
      link_to('Login', login_path, :class => 'button')
    end
  end
end

app/views/home/index.html.haml
= link_to('Let\'s Get Started', simulation_path, :class => 'button radius medium success simhome')

<img id="squash_image" src="http://squashuk.com/wp-content/uploads/2011/03/MG_0144.jpg"></div>

app/views/layouts/_nav.html.erb
<link href='http://fonts.googleapis.com/css?family=Libre+Baskerville:400,400italic' rel='stylesheet' type='text/css'>

<div class="row">
  <div class="large-12 columns">
    <div class="nav-bar right">
     <ul class="button-group aligncenter">
       <li><%= link_to('Users', users_path, :class => 'button') %></li>
       <li><%= link_to('New User', new_user_path, :class => 'button') %></li>
       <li><%= link_to('Simulation Engine', simulation_path, :class => 'button') %></li>
       <li id = "rankings_link"><%= link_to('Individual Rankings', ladder_path, :class => 'button') %></li>
       <li><%= intellinav %></li>
     </ul>
    </div>
    <br>
  </div>
  <h2 id="logo" class="aligncenter">Squash the Competition</h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Squash the Competition</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
  <%= render :partial => 'layouts/nav' %>
  <div class='row'>
    <div class="large-12 columns background">
      <%= yield %>
    </div>
  </div>
  <%= render :partial => 'layouts/footer' %>
</body>
</html>

app/views/pages/_player.html.haml
.row.playerName
  .large-6.columns
    %input.aligncenter{:id => "Team1Name#{@i}", :type => "text", :placeholder => "\##{@i} Name"}
  .large-6.columns
    %input.aligncenter{:id => "probability#{@i}", :placeholder => "Win Probability", :type => "text"}

app/views/pages/_player2.html.haml
.row.playerName
  .large-6.columns
    %input.aligncenter{:id => "team2probability" + @i.to_s, :placeholder => "Win Probability", :type => "text"}
  .large-6.columns
    %input.aligncenter{:id => "Team2Name#{@i}", :type => "text", :placeholder => "\##{@i} Name"}

app/views/pages/datatable.html.haml
%table#datatable
  %tbody
    %th Individual Win %
    %th Team Win %
    %th 9-0
    %th 8-1
    %th 7-2
    %th 6-3
    %th 5-4
    %th 4-5
    %th 3-6
    %th 2-7
    %th 1-8
    %th 0-9
    %tr
      %td 90%
      %td 99%+
      %td 39%
      %td 38%
      %td 18%
      %td 4%
      %td 1%
      %td -%
      %td -%
      %td -%
      %td -%
      %td -%
    %tr
      %td 80%
      %td 98%
      %td 14%
      %td 30%
      %td 30%
      %td 18%
      %td 7%
      %td 1%
      %td -%
      %td -%
      %td -%
      %td -%
    %tr
      %td 70%
      %td 90%
      %td 4%
      %td 16%
      %td 27%
      %td 27%
      %td 17%
      %td 7%
      %td 2%
      %td -%
      %td -%
      %td -%
    %tr
      %td 60%
      %td 72%
      %td 1%
      %td 6%
      %td 16%
      %td 25%
      %td 25%
      %td 17%
      %td 8%
      %td 2%
      %td -%
      %td -%
    %tr
      %td 50%
      %td 50%
      %td -%
      %td 2%
      %td 6%
      %td 17%
      %td 25%
      %td 25%
      %td 17%
      %td 6%
      %td 2%
      %td -%

app/views/pages/ladder.html.haml
%div.row
  %div.col.header Ranking
  %div.col.header Player
  %div.col.header Rating
  %div.col.header Team
  %br
%div.row
  -@ladder.each do |player|
    %div.col= @ladder.index(player) + 1
    %div.col= player.name
    %div.col= sprintf("%0.4f", player.rating)
    %div.col= player.team
    %br

app/views/pages/rankings.html.haml
#rankings
  %ol

app/views/pages/simulation.html.haml
%h4#instructions
  Input number of simulations, teams, and probabilities. The simulator does the rest!

#after
  .row
    .large-4.columns
      &nbsp;
    .large-4.columns.aligncenter
      %input#num_of_simulations{:placeholder => "Number of Simulations", :type => "text"}
    .large-4.columns

  .row
    .large-5.columns
      %p
        Team 1:
        = select_tag('team', options_from_collection_for_select(@top_20.order(:name), :team_id, :name), :prompt => 'Select Team', :id => 'team1')
      -for @i in 1..9
        = render :partial => 'player'

    .large-2.columns
      %p
      %p
        .row.playerName
          #slider1
          #s1
      %p
        .row.playerName
          #slider2
          #s2
      %p
        .row.playerName
          #slider3
          #s3
      %p
        .row.playerName
          #slider4
          #s4
      %p
        .row.playerName
          #slider5
          #s5
      %p
        .row.playerName
          #slider6
          #s6
      %p
        .row.playerName
          #slider7
          #s7
      %p
        .row.playerName
          #slider8
          #s8
      %p
        .row.playerName
          #slider9
          #s9


    / TEAM 2 STARTS HERE
    .large-5.columns
      %p
        Team 2:
        = select_tag('team', options_from_collection_for_select(@top_20, :team_id, :name), :prompt => 'Select Team', :id => 'team2')
      -for @i in 1..9
        = render :partial => 'player2'

#result.hide

.row
  #chart.hide.aligncenter

%buttons
  .row
    .large-5.columns
      #simulate_button.button.aligncenter Simulate!
    .large-2.columns
    .large-5.columns
      #reset_button.button Reset!

app/views/session/new.html.haml
.row
  .five.columns
    = form_tag '/login' do
      = label_tag :email
      = text_field_tag :email, nil, :autofocus => true
      = label_tag :password
      = password_field_tag :password
      = submit_tag 'Login to Squash Simulator', :class => 'button radius'
  .seven.columns

app/views/users/_form.html.haml
.row
  .five.columns
    = form_for @user, :remote => true do |f|
      = f.label :email
      = f.text_field :email, :autofocus => true
      = f.label :team
      = f.text_field :team
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation, 'Password Confirmation'
      = f.password_field :password_confirmation
      = f.submit nil, :class => 'button radius'
  .seven.columns

app/views/users/_users.html.haml
- @users.each do |user|
  %li= user.email

app/views/users/create.js.erb
$('#new_user').empty();
$('#users').empty();
$('#users').append('<%=j render(:partial => 'users') %>');

app/views/users/index.html.haml
= link_to('New User', new_user_path, :remote => true, :class => 'button radius medium success disappear')

#new_user
%ol#users
  =render(:partial => 'users')

app/views/users/new.html.haml
%h3 New User
= render(:partial => 'form')

app/views/users/new.js.erb
$('#new_user').append('<%=j render(:partial => 'form') %>');
$('#users').empty();
$('.disappear').hide();